apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: anglerfish-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/anglerfish-dotnet-basic-gitops